# ベースイメージとしてNode.jsの最新のLTSバージョンを使用
FROM node:20

# 環境変数の設定
ENV NODE_ENV=development

# 作業ディレクトリを作成
WORKDIR /app

# package.jsonとpackage-lock.jsonをコピー
COPY package*.json ./

# 依存関係をインストール
RUN npm install

# アプリケーションのソースコードをコピー
COPY . .

# アプリケーションを実行するためのポートを指定
EXPOSE 3001

# アプリケーションを起動
CMD ["npm", "run", "dev"]
